In [ ]:

#  This NoteBook contains cdoe from the Ch 04 folder ..
#



In [ ]:

%load_ext autoreload
%autoreload 2

%xmode Minimal

#  Setting display options 

import pandas as pd
   #
pd.set_option("display.width", 480)

#  Sets horizontal scroll for wide outputs
#
from IPython.display import display, HTML
display(HTML(""))

from tabulate import tabulate


   ###

    
#  How to use tabulate-
#
l_result = [{ "col1": 20, "col2": 30}]
   #
print(tabulate(l_result, headers='keys', tablefmt='psql', showindex=False))


print("--")


In [ ]:


import numpy as np
import matplotlib.pyplot as plt 

d = [[ 0.6930, -1.1259, -1.5318,  0.9525,  1.1824],
     [ 0.5464, -0.0120,  0.5051, -0.0192, -0.1141],
     [ 0.8912,  1.3826,  1.5193, -1.1996, -1.1403],
     [ 1.1690,  0.4970, -0.1712, -0.5340,  0.3047],
     [-0.9221, -0.1071,  0.3079, -0.3885, -0.4753],
     [ 1.5699, -1.4767,  0.3327,  1.4714,  1.1807],
     [-0.3479,  0.4775,  1.8823, -1.4031, -0.7396],
     [ 0.0887, -0.4353, -1.7377, -1.2349,  1.7456],
     [ 1.0775,  0.9524,  1.2475,  0.7291, -1.1207],
     [-1.4657,  0.9250, -1.0446,  0.4262, -1.0279],
     [-1.3332,  1.4501,  0.0323,  1.1102, -0.8966],
     [ 0.3005, -1.4500, -0.2615,  1.7033, -0.2505],
     [-1.4377, -0.2472, -0.4340, -0.7032,  0.3362],
     [ 0.3016, -1.5527, -0.6213,  0.1780, -0.7517],
     [-1.1315,  0.7225, -0.0250, -1.0881,  1.7674]]

d = np.array(d)

plt.boxplot(d)
plt.show()

print("--")


In [4]:

from sklearn import preprocessing
import numpy as np

x_array = np.array([2,3,5,6,7,4,8,7,6,0])
print(x_array)

#  headers = ["col 1", "col 2", "col 3", "c4", "c5", "c6", "c7", "c8"]
#  print(tabulate(x_array, headers, tablefmt='fancy_grid'))


print()

normalized_arr = preprocessing.normalize([x_array])
print(normalized_arr)
print()

x_array_2 = x_array.reshape((5, 2))
print(x_array_2)
print()

x_array_2_norm = preprocessing.normalize(x_array_2)
print(x_array_2_norm)



[2 3 5 6 7 4 8 7 6 0]

[[0.11785113 0.1767767  0.29462783 0.35355339 0.41247896 0.23570226
  0.47140452 0.41247896 0.35355339 0.        ]]

[[2 3]
 [5 6]
 [7 4]
 [8 7]
 [6 0]]

[[0.5547002  0.83205029]
 [0.6401844  0.76822128]
 [0.86824314 0.49613894]
 [0.75257669 0.65850461]
 [1.         0.        ]]


In [ ]:

x_array = np.array([2,3,5,6,7,4,8,7,6,0])
print(x_array)

#  headers = ["col 1", "col 2", "col 3", "c4", "c5", "c6", "c7", "c8"]
#  print(tabulate(x_array, headers, tablefmt='fancy_grid'))


print()

normalized_arr = preprocessing.normalize([x_array])




In [ ]:

#######################################################################


In [ ]:

import numpy as np
from sklearn.datasets import make_classification

a,b = make_classification(n_samples=10000, weights=(0.9,0.1))
idx = np.where(b == 0)[0]
x0 = a[idx,:]
y0 = b[idx]
idx = np.where(b == 1)[0]
x1 = a[idx,:]
y1 = b[idx]

idx = np.argsort(np.random.random(y0.shape))
y0 = y0[idx]
x0 = x0[idx]
idx = np.argsort(np.random.random(y1.shape))
y1 = y1[idx]
x1 = x1[idx]

ntrn0 = int(0.9*x0.shape[0])
ntrn1 = int(0.9*x1.shape[0])
xtrn = np.zeros((int(ntrn0+ntrn1),20))
ytrn = np.zeros(int(ntrn0+ntrn1))
xtrn[:ntrn0] = x0[:ntrn0]
xtrn[ntrn0:] = x1[:ntrn1]
ytrn[:ntrn0] = y0[:ntrn0]
ytrn[ntrn0:] = y1[:ntrn1]

n0 = int(x0.shape[0]-ntrn0)
n1 = int(x1.shape[0]-ntrn1)
xval = np.zeros((int(n0/2+n1/2),20))
yval = np.zeros(int(n0/2+n1/2))
xval[:(n0//2)] = x0[ntrn0:(ntrn0+n0//2)]
xval[(n0//2):] = x1[ntrn1:(ntrn1+n1//2)]
yval[:(n0//2)] = y0[ntrn0:(ntrn0+n0//2)]
yval[(n0//2):] = y1[ntrn1:(ntrn1+n1//2)]

xtst = np.concatenate((x0[(ntrn0+n0//2):],x1[(ntrn1+n1//2):]))
ytst = np.concatenate((y0[(ntrn0+n0//2):],y1[(ntrn1+n1//2):]))

print("--")


In [ ]:

import numpy as np
from sklearn.datasets import make_classification

x,y = make_classification(n_samples=10000, weights=(0.9,0.1))
idx = np.argsort(np.random.random(y.shape[0]))
x = x[idx]
y = y[idx]

ntrn = int(0.9*y.shape[0])
nval = int(0.05*y.shape[0])

xtrn = x[:ntrn]
ytrn = y[:ntrn]
xval = x[ntrn:(ntrn+nval)]
yval = y[ntrn:(ntrn+nval)]
xtst = x[(ntrn+nval):]
ytst = y[(ntrn+nval):]

print("--")


In [ ]:

import numpy as np

f = [0.3408,3.0150,4.3465,2.1271,2.7561,
     2.7887,4.8231,0.0705,3.9897,0.9804,
     2.3944,2.0085,1.7821,1.5362,2.3190]
f = np.array(f)

print
print("mean  = %0.4f" % f.mean())
print("std   = %0.4f" % f.std())
print("SE    = %0.4f" % (f.std()/np.sqrt(f.shape[0])))
print("median= %0.4f" % np.median(f))
print("min   = %0.4f" % f.min())
print("max   = %0.4f" % f.max())

print("--")
