In [ ]:

#  Compulsaries; randomizing nupmy arrays, and more


In [1]:

import numpy as np

print("--")


--


In [ ]:

#  np_arr = np.arange(0, 9, 1, dtype = int)
#  print(np_arr)

#  Generate an array with specific values
#
np_arr1 = np.array([[1, 2, 0], [3, 4, 0], [5, 6, 0], [7, 8, 0]])
print(np_arr1)
print()

#  Make a copy of np_arr1
#
np_arr2 = np.copy(np_arr1)
print(np_arr2)
print()

#  Resort/randomize the 'rows' within the array
#
l_idx = np.argsort(np.random.random(np_arr2.shape[0]))
print(l_idx)
print()
np_arr2 = np_arr2[l_idx]
print(np_arr1)
print(np_arr2)
print()


#  Sample data,
#
#     [[1 2 0]
#      [3 4 0]
#      [5 6 0]
#      [7 8 0]]
#     
#     [[1 2 0]
#      [3 4 0]
#      [5 6 0]
#      [7 8 0]]
#     
#     [0 3 1 2]
#     
#     [[1 2 0]
#      [3 4 0]
#      [5 6 0]
#      [7 8 0]]
#     [[1 2 0]
#      [7 8 0]
#      [3 4 0]
#      [5 6 0]]


In [ ]:

#  Making a numpy array of a given shape 
#

np_arr8 = np.zeros((np_arr2.shape[0], np_arr2.shape[1]), dtype = int)
print(np_arr8)
print()


In [ ]:

#  Copy arr1 (we'll use np_arr3), randomize the 'values' within each 'row'
#

#  Make a copy of np_arr1
#
np_arr3 = np.copy(np_arr1)
print(np_arr3)
print()

#  Shuffle the values, not the row order
#
for i in range(np_arr3.shape[0]):
   np.random.shuffle(np_arr3[i, :])

print(np_arr3)

#  Sample output
#
#     [[1 2 0]
#      [3 4 0]
#      [5 6 0]
#      [7 8 0]]
#     
#     [[0 1 2]
#      [4 0 3]
#      [6 5 0]
#      [0 8 7]]


In [47]:

#  Different than the cell above, randomization all rows by just one pattern
#

np_arrA = np.array([[1, 2, 0], [3, 4, 0], [5, 6, 0], [7, 8, 0], [11, 12, 13]])


#  Make a copy of np_arrA
#
np_arr4 = np.copy(np_arrA)
print(np_arr4)
print()


#  Create a numpy array which will be our randomization pattern
#
#     (We don't check that the new/random pattern is different than the source,
#      which can happen (1 / length!) number of times.
#
np_ran = np.arange(0, np_arr4.shape[1], 1, dtype = int)
print(np_ran)
np.random.shuffle(np_ran)
print(np_ran)
print()


#  Apply the actual 'randomization'
#
for i in range(np_arr4.shape[0]):
   l_tmp = np.zeros(np_arr4.shape[1], dtype = int)
   for j in range(np_arr4.shape[1]):
      l_tmp[j] = np_arr4[i][ np_ran[j] ]
   np_arr4[i, :] = l_tmp[:]
        
print(np_arr4)        

#  Sample output
#
#     [[1 2 0]
#      [3 4 0]
#      [5 6 0]
#      [7 8 0]]
#     
#     [0 1 2]
#     [2 1 0]
#     
#     [[0 2 1]
#      [0 4 3]
#      [0 6 5]
#      [0 8 7]]


[[ 1  2  0]
 [ 3  4  0]
 [ 5  6  0]
 [ 7  8  0]
 [11 12 13]]

[0 1 2]
[2 1 0]

[[ 0  2  1]
 [ 0  4  3]
 [ 0  6  5]
 [ 0  8  7]
 [13 12 11]]


In [ ]:

#  Extracting just given columns from a numpy array 
#

np_arrB = np.array([[1, 2, 0, 8, 9], [3, 4, 0], [5, 6, 0], [7, 8, 0], [11, 12, 13]])


#  Make a copy of np_arrA
#
np_arr5 = np.copy(np_arrB)
print(np_arr5)
print()



