In [20]:

import numpy as np


#  np_arr = np.arange(0, 9, 1, dtype=int)
#  print(np_arr)

#  Generate an array with specific values
#
np_arr1 = np.array([[1, 2, 0], [3, 4, 0], [5, 6, 0], [7, 8, 0]])
print(np_arr1)
print()

#  Make copies of np_arr1
#
np_arr2 = np.copy(np_arr1)
np_arr3 = np.copy(np_arr1)
np_arr4 = np.copy(np_arr1)
print(np_arr2)
print()

#  Resort/randomize the 'rows' within the array
#
l_idx = np.argsort(np.random.random(np_arr2.shape[0]))
print(l_idx)
print()
np_arr2 = np_arr2[l_idx]
print(np_arr1)
print(np_arr2)
print()


[[1 2 0]
 [3 4 0]
 [5 6 0]
 [7 8 0]]

[[1 2 0]
 [3 4 0]
 [5 6 0]
 [7 8 0]]

[2 3 0 1]

[[1 2 0]
 [3 4 0]
 [5 6 0]
 [7 8 0]]
[[5 6 0]
 [7 8 0]
 [1 2 0]
 [3 4 0]]



In [30]:

#  Go back to arr1 (we'll use np_arr3), randomize the 'values' within each 'row'
#
np_arr8 = np.zeros((np_arr3.shape[0], np_arr3.shape[1]), dtype = int)
print(np_arr8)
print()
   #
for i in range(np_arr3.shape[0]):
   np.random.shuffle(np_arr3[i])
    
    
   #  np.argsort(np.random.random(np_arr3[i])) 
   #  print(np_arr3[i])



#  aaa = np.copy(np_arr3[i])



[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]



TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'