In [8]:

import numpy as np


#  np_arr = np.arange(0, 9, 1, dtype=int)
#  print(np_arr)

np_arr = np.array([[1, 2, 0], [3, 4, 0], [5, 6, 0], [7, 8, 0]])

l_idx = np.print(np_arr)






[[1 2 0]
 [3 4 0]
 [5 6 0]
 [7 8 0]]
